tags:
  domain/study:
    count: 56
    examples:
    - 700_База_Данных/Знания/Example_Note_Study.md
  topic/sample:
    count: 1
    examples:
    - 700_База_Данных/Знания/Example_Note_Topic.md
  domain/creative:
    count: 56
    examples: []
  topic/creative-thinking:
    count: 5
    examples: []
  topic/curiosity:
    count: 8
    examples: []
  domain/life:
    count: 50
    examples: []
  topic/barber:
    count: 3
    examples: []
  topic/hairstyle:
    count: 3
    examples: []
  domain/tech:
    count: 10
    examples: []
  topic/cursor:
    count: 1
    examples: []
  topic/software-installation:
    count: 1
    examples: []
  domain/entertainment:
    count: 76
    examples: []
  topic/ufo:
    count: 2
    examples: []
  topic/beauty:
    count: 16
    examples: []
  topic/spa:
    count: 4
    examples: []
  topic/religion:
    count: 3
    examples: []
  topic/spiritual-journey:
    count: 9
    examples: []
  source/youtube:
    count: 64
    examples: []
  topic/etiquette:
    count: 7
    examples: []
  topic/sauna:
    count: 4
    examples: []
  topic/accident:
    count: 9
    examples: []
  topic/ancient-texts:
    count: 2
    examples: []
  source/tiktok:
    count: 14
    examples: []
  topic/comedy:
    count: 2
    examples: []
  topic/social-media:
    count: 1
    examples: []
  topic/communication:
    count: 2
    examples: []
  topic/podcast:
    count: 2
    examples: []
  domain/travel:
    count: 10
    examples: []
  topic/freedom:
    count: 3
    examples: []
  topic/music:
    count: 31
    examples: []
  topic/children:
    count: 2
    examples: []
  topic/family:
    count: 3
    examples: []
  topic/athlete:
    count: 1
    examples: []
  domain/food:
    count: 5
    examples: []
  topic/grandmothers:
    count: 1
    examples: []
  topic/restaurant:
    count: 1
    examples: []
  topic/neuroplasticity:
    count: 1
    examples: []
  topic/psychology:
    count: 1
    examples: []
  domain/business:
    count: 2
    examples: []
  topic/business:
    count: 1
    examples: []
  topic/transparency:
    count: 1
    examples: []
  topic/simulation:
    count: 1
    examples: []
  topic/lgbtq:
    count: 1
    examples: []
  domain/health:
    count: 16
    examples: []
  topic/health:
    count: 8
    examples: []
  topic/medicine:
    count: 1
    examples: []
  topic/vitamins:
    count: 1
    examples: []
  domain/career:
    count: 3
    examples: []
  topic/public-speaking:
    count: 1
    examples: []
  topic/fire-safety:
    count: 1
    examples: []
  topic/military:
    count: 1
    examples: []
  topic/haircare:
    count: 1
    examples: []
  topic/herbs:
    count: 1
    examples: []
  topic/sleep:
    count: 1
    examples: []
  topic/water-filter:
    count: 1
    examples: []
  topic/hygiene:
    count: 1
    examples: []
  topic/fragrance:
    count: 1
    examples: []
  topic/indoor-plants:
    count: 1
    examples: []
  topic/plants:
    count: 1
    examples: []
  topic/news:
    count: 1
    examples: []
  topic/food-tracking:
    count: 1
    examples: []
  topic/nutrition:
    count: 1
    examples: []
  topic/pinterest:
    count: 1
    examples: []
  topic/gaming:
    count: 1
    examples: []
  topic/mahjong:
    count: 1
    examples: []
  topic/juggling:
    count: 1
    examples: []
  topic/cosmetics:
    count: 1
    examples: []
  topic/skincare:
    count: 1
    examples: []
  topic/evolution:
    count: 2
    examples: []
  topic/humor:
    count: 4
    examples: []
  topic/neuroscience:
    count: 3
    examples: []
  topic/cambridge:
    count: 2
    examples: []
  topic/intellectual-capital:
    count: 2
    examples: []
  topic/ballet:
    count: 2
    examples: []
  topic/film:
    count: 6
    examples: []
  topic/adventure:
    count: 2
    examples: []
  topic/collectibles:
    count: 4
    examples: []
  topic/dj:
    count: 2
    examples: []
  topic/egypt:
    count: 3
    examples: []
  topic/antarctica:
    count: 1
    examples: []
  topic/neon-genesis-evangelion:
    count: 2
    examples: []
  topic/sports:
    count: 2
    examples: []
  topic/watches:
    count: 2
    examples: []
  subtype/meme:
    count: 4
    examples: []
  subtype/screenshot:
    count: 2
    examples: []
  topic/physics:
    count: 2
    examples: []
  topic/quantum-mechanics:
    count: 2
    examples: []
  topic/relativity:
    count: 2
    examples: []
  topic/park:
    count: 3
    examples: []
  topic/survival:
    count: 3
    examples: []
  topic/geopolitics:
    count: 2
    examples: []
  topic/ukraine:
    count: 2
    examples: []
  topic/ab-testing:
    count: 1
    examples: []
  topic/internet:
    count: 1
    examples: []
  topic/conflict:
    count: 1
    examples: []
  topic/parents:
    count: 1
    examples: []
  topic/self-presentation:
    count: 1
    examples: []
  topic/motivation:
    count: 3
    examples: []
  topic/urban-exploration:
    count: 1
    examples: []
  topic/nfc:
    count: 1
    examples: []
  topic/self-discovery:
    count: 2
    examples: []
  topic/mystery:
    count: 2
    examples: []
  topic/winter-adventures:
    count: 2
    examples: []
  topic/beverages:
    count: 3
    examples: []
  topic/indonesia:
    count: 1
    examples: []
  topic/romance:
    count: 1
    examples: []
  topic/college:
    count: 1
    examples: []
  topic/necromancer:
    count: 1
    examples: []
namespaces:
  domain:
  - business
  - career
  - creative
  - entertainment
  - food
  - health
  - life
  - study
  - tech
  - travel
  topic:
  - ab-testing
  - accident
  - adventure
  - ancient-texts
  - antarctica
  - athlete
  - ballet
  - barber
  - beauty
  - beverages
  - business
  - cambridge
  - children
  - collectibles
  - college
  - comedy
  - communication
  - conflict
  - cosmetics
  - creative-thinking
  - curiosity
  - cursor
  - dj
  - egypt
  - etiquette
  - evolution
  - family
  - film
  - fire-safety
  - food-tracking
  - fragrance
  - freedom
  - gaming
  - geopolitics
  - grandmothers
  - haircare
  - hairstyle
  - health
  - herbs
  - humor
  - hygiene
  - indonesia
  - indoor-plants
  - intellectual-capital
  - internet
  - juggling
  - lgbtq
  - mahjong
  - medicine
  - military
  - motivation
  - music
  - mystery
  - necromancer
  - neon-genesis-evangelion
  - neuroplasticity
  - neuroscience
  - news
  - nfc
  - nutrition
  - parents
  - park
  - physics
  - pinterest
  - plants
  - podcast
  - psychology
  - public-speaking
  - quantum-mechanics
  - relativity
  - religion
  - restaurant
  - romance
  - sample
  - sauna
  - self-discovery
  - self-presentation
  - simulation
  - skincare
  - sleep
  - social-media
  - software-installation
  - spa
  - spiritual-journey
  - sports
  - survival
  - transparency
  - ufo
  - ukraine
  - urban-exploration
  - vitamins
  - watches
  - water-filter
  - winter-adventures
  source:
  - tiktok
  - youtube
  subtype:
  - meme
  - screenshot
total_notes: 0
notes_with_tags: 0
