#!/usr/bin/env python3
"""Write config/agent/capabilities.yaml — compose any module/connector mix (not fixed personas)."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import yaml

from shared.agent.config import agent_config_dir
from shared.capabilities.builder import build_capabilities_document
from shared.capabilities.compose import SYNC_PROFILE_AUTO
from shared.capabilities.presets import PRESET_CUSTOM, PRESET_FULL, list_preset_names
from shared.capabilities.profile import (
    CONNECTOR_CORPORATE_BADGE,
    _ALL_CONNECTORS,
    _ALL_MODULES,
    clear_capabilities_cache,
)
from shared.setup.env_patch import collect_env_hints, patch_env_file


def _write_yaml(path: Path, doc: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Generated by scripts/apply_capabilities_profile.py — gitignored.\n"
        "# Absent file + OBSIDIAN_AGENT_FULL_INSTALL=1 = full product; else OSS starter.\n\n"
    )
    body = yaml.safe_dump(doc, allow_unicode=True, sort_keys=False)
    path.write_text(header + body, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Compose capabilities.yaml: enable only the Telegram domains and data sources you need.",
    )
    parser.add_argument(
        "--preset",
        default=PRESET_CUSTOM,
        choices=list_preset_names(),
        help="Starting point (default: custom = all modules/connectors off, then flags)",
    )
    parser.add_argument("--write", action="store_true", help="Write config/agent/capabilities.yaml")
    parser.add_argument("--dry-run", action="store_true", help="Print YAML to stdout only")
    parser.add_argument(
        "--only-modules",
        nargs="+",
        choices=list(_ALL_MODULES),
        metavar="MODULE",
        help="Enable only these modules (disables the rest), e.g. planning for kanban-only",
    )
    for mod in _ALL_MODULES:
        parser.add_argument(f"--{mod}", action="store_true", help=f"Enable module {mod}")
        parser.add_argument(f"--no-{mod}", action="store_true", help=f"Disable module {mod}")
    for conn in _ALL_CONNECTORS:
        flag = conn.replace("_", "-")
        parser.add_argument(f"--{flag}", action="store_true", help=f"Enable connector {conn}")
    parser.add_argument("--sync-profile", default=SYNC_PROFILE_AUTO, help="sync.profile or auto (default)")
    parser.add_argument(
        "--patch-env",
        action="store_true",
        help="Append missing .env keys (never overwrite values)",
    )
    parser.add_argument(
        "--setup-badge",
        action="store_true",
        help="Copy finance_bot/config/badge.yaml.example → badge.yaml if missing",
    )
    parser.add_argument("--broker", action="store_true", dest="broker_sync")
    parser.add_argument("--gmail-health", action="store_true", dest="gmail_health_pipeline")
    parser.add_argument("--smoke", action="store_true", help="Run scripts/onboarding_smoke.py after write")
    args = parser.parse_args()

    modules: dict[str, bool] = {}
    if args.only_modules:
        for m in _ALL_MODULES:
            modules[m] = m in args.only_modules
    for m in _ALL_MODULES:
        if getattr(args, m, False):
            modules[m] = True
        if getattr(args, f"no_{m}", False):
            modules[m] = False

    connectors: dict[str, bool] = {}
    for c in _ALL_CONNECTORS:
        if getattr(args, c, False):
            connectors[c] = True

    doc = build_capabilities_document(
        args.preset,
        modules=modules or None,
        connectors=connectors or None,
        sync_profile=args.sync_profile,
        only_modules=args.only_modules,
        broker_sync=True if args.broker_sync else None,
        manual_broker=True if getattr(args, "manual_broker_accounts", False) else None,
        apple_health=True if args.apple_health else None,
        gmail_health=True if args.gmail_health_pipeline else None,
        apple_calendar=True if args.apple_calendar else None,
        mac_context=True if args.mac_context else None,
        knowledge_serendipity=True if args.knowledge_serendipity else None,
    )

    if args.dry_run or not args.write:
        print(yaml.safe_dump(doc, allow_unicode=True, sort_keys=False))
        if not args.write:
            print("# Dry-run only. Pass --write to save.", file=sys.stderr)
            return 0

    out = agent_config_dir() / "capabilities.yaml"
    _write_yaml(out, doc)
    clear_capabilities_cache()
    print(f"Wrote {out}")
    print(f"sync.profile={doc.get('sync', {}).get('profile')}")

    repo_root = _ROOT
    connectors_map = doc.get("connectors") or {}
    modules_map = doc.get("modules") or {}
    if args.setup_badge or connectors_map.get(CONNECTOR_CORPORATE_BADGE):
        badge_example = repo_root / "finance_bot" / "config" / "badge.yaml.example"
        badge_out = repo_root / "finance_bot" / "config" / "badge.yaml"
        if badge_example.is_file() and not badge_out.is_file():
            badge_out.write_text(badge_example.read_text(encoding="utf-8"), encoding="utf-8")
            print(f"Created {badge_out} — set enabled: true and limits in file")

    if args.patch_env:
        env_path = repo_root / ".env"
        if not env_path.is_file():
            example = repo_root / ".env.example"
            if example.is_file():
                env_path.write_text(example.read_text(encoding="utf-8"), encoding="utf-8")
        hints = collect_env_hints(connectors_map, modules=modules_map)
        added = patch_env_file(env_path, hints)
        if added:
            print(f"Patched {env_path}: added {len(added)} key(s)")
        else:
            print(f"No new keys for {env_path}")

    if args.smoke:
        import subprocess

        smoke = _ROOT / "scripts" / "onboarding_smoke.py"
        subprocess.run([sys.executable, str(smoke)], cwd=str(_ROOT), check=False)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
